services:
  php:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - ./:/app
    networks:
      - cinema
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "1010:80"
    depends_on:
      - php
    networks:
      - cinema

  db:
    image: mariadb:10.5
    volumes:
      - .docker/mariadb/databases:/var/lib/mysql
      - .docker/mariadb/sql-files:/sql-files
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    working_dir: /sql-files
    ports:
      - ${DB_PORT_SUCUNDARIA}:${DB_PORT}

networks:
  cinema:
    driver: bridge
